### ISSUE TITLE
SD绘画功能无法使用

### ISSUE THREAD

**Issue by dfggggx198601** [yangjian102621/chatgpt-plus#44]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

已经按照说明在config.toml里，配置了sd的相关参数

经过docker logs -f 查看，有如下报错信息
2023/10/22 23:01:52 /root/chatgpt-plus/api/handler/chatimpl/chat_handler.go:96 record not found
[1.324ms] [rows:0] SELECT * FROM `chatgpt_chat_items` WHERE chat_id='18e07831-8b72-4d48-8da7-892576a40e61' AND `chatgpt_chat_items`.`deleted_at` IS NULL ORDER BY `chatgpt_chat_items`.`id` LIMIT 1
2023-10-22T23:01:52.770+0800    INFO    chatimpl/chat_handler.go:107    New websocket connected, IP: 104.28.213.171, Username: 13148924944
2023-10-22T23:01:54.259+0800    INFO    sd/service.go:63        Consuming Task: {Id:70 SessionId:qaef98yxas06yz2r4t9jl5rhnnngdv4aifna32ztik Src:img Type:image UserId:96 Prompt:A beautiful Chinese girl riding on a tiger Params:{TaskId:task(jo8t50vpuavcc7u) Prompt:A beautiful Chinese girl riding on a tiger NegativePrompt:nsfw, paintings, cartoon, anime, sketches, low quality,easynegative,ng_deepnegative _v1 75t,(worst quality:2),(low quality:2),(normalquality:2),lowres,bad anatomy,bad hands,normal quality,((monochrome)),((grayscale)),((watermark)) Steps:20 Sampler:Euler a FaceFix:false CfgScale:7 Seed:-1 Height:1024 Width:1024 HdFix:false HdRedrawRate:0.3 HdScale:2 HdScaleAlg:ESRGAN_4x HdSteps:0} RetryCount:0}
2023-10-22T23:01:54.259+0800    ERROR   sd/service.go:66        绘画任务执行失败：error with load text2img json template file: open res/text2img.json: no such file or directory
2023-10-22T23:01:57.261+0800    INFO    sd/service.go:63        Consuming Task: {Id:70 SessionId:qaef98yxas06yz2r4t9jl5rhnnngdv4aifna32ztik Src:img Type:image UserId:96 Prompt:A beautiful Chinese girl riding on a tiger Params:{TaskId:task(jo8t50vpuavcc7u) Prompt:A beautiful Chinese girl riding on a tiger NegativePrompt:nsfw, paintings, cartoon, anime, sketches, low quality,easynegative,ng_deepnegative _v1 75t,(worst quality:2),(low quality:2),(normalquality:2),lowres,bad anatomy,bad hands,normal quality,((monochrome)),((grayscale)),((watermark)) Steps:20 Sampler:Euler a FaceFix:false CfgScale:7 Seed:-1 Height:1024 Width:1024 HdFix:false HdRedrawRate:0.3 HdScale:2 HdScaleAlg:ESRGAN_4x HdSteps:0} RetryCount:0}
并且这个日志信息在不停增加，也不知道怎么停止

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
请提供 config.toml 配置信息，以及 docker-compose.yaml

**Comment by dfggggx198601** [comment]
以下是docker-compose.yaml
version: '3'
services:
  # 后端 API 程序
  chatgpt-plus-api:
    image: dfggggx-chatgpt-api-3.1.6-new:latest
    container_name: chatgpt-plus-api
    restart: always
    environment:
      - DEBUG=false
      - LOG_LEVEL=info
      - CONFIG_FILE=config.toml
    ports:
      - "5678:5678"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./conf/config.toml:/var/www/app/config.toml
      - ./logs:/var/www/app/logs
      - ./static:/var/www/app/static
      - ./res:/var/www/app/res

  # 前端应用
  chatgpt-plus-web:
    image: dfggggx-chatgpt-web-3.1.6-new:latest
    container_name: chatgpt-plus-web
    restart: always
    ports:
      - "8088:8080"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl

以下是config.toml
Listen = "0.0.0.0:5678"
#ProxyURL = "" # 如 http://127.0.0.1:7777
MysqlDns = "root:12345678@tcp(150.230.215.211:3307)/chatgpt_plus?charset=utf8&parseTime=True&loc=Local"
StaticDir = "./static" # 静态资源的目录
StaticUrl = "/static" # 静态资源访问 URL
AesEncryptKey = ""
WeChatBot = false

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80" # 注意：这个是 JWT Token 授权密钥，生产环境请务必更换
  MaxAge = 86400

[Manager]
  Username = "admin"
  Password = "admin123" # 如果是生产环境的话，这里管理员的密码记得修改

[Redis] # redis 配置信息
  Host = "150.230.215.211"
  Port = 6379
  Password = ""
  DB = 0
[SdConfig]
  Enabled = true
  ApiURL = "http://54755ea8.r16.cpolar.top/sdapi/v1/txt2img"
  ApiKey = ""
  Txt2ImgJsonPath = "res/text2img.json"

**Comment by dfggggx198601** [comment]
API的话，我是用了内网穿透的，已经通过postman测试可以出图，现在的问题是提交绘画任务后，api容器会重启，log提示如下
2023-10-23T22:26:08.970+0800    INFO    sd/service.go:84        add a new MidJourney Task: {Id:75 SessionId:qaef98yxas06yz2r4t9jl5rhnnngdv4aifna32ztik Src:img Type:image UserId:96 Prompt:A beautiful Chinese girl riding on a tiger Params:{TaskId:task(yxbnv9x32l3b03q) Prompt:A beautiful Chinese girl riding on a tiger NegativePrompt:nsfw, paintings, cartoon, anime, sketches, low quality,easynegative,ng_deepnegative _v1 75t,(worst quality:2),(low quality:2),(normalquality:2),lowres,bad anatomy,bad hands,normal quality,((monochrome)),((grayscale)),((watermark)) Steps:20 Sampler:Euler a FaceFix:false CfgScale:7 Seed:-1 Height:1024 Width:1024 HdFix:false HdRedrawRate:0.3 HdScale:2 HdScaleAlg:ESRGAN_4x HdSteps:0} RetryCount:0}
2023-10-23T22:26:08.971+0800    INFO    sd/service.go:63        Consuming Task: {Id:75 SessionId:qaef98yxas06yz2r4t9jl5rhnnngdv4aifna32ztik Src:img Type:image UserId:96 Prompt:A beautiful Chinese girl riding on a tiger Params:{TaskId:task(yxbnv9x32l3b03q) Prompt:A beautiful Chinese girl riding on a tiger NegativePrompt:nsfw, paintings, cartoon, anime, sketches, low quality,easynegative,ng_deepnegative _v1 75t,(worst quality:2),(low quality:2),(normalquality:2),lowres,bad anatomy,bad hands,normal quality,((monochrome)),((grayscale)),((watermark)) Steps:20 Sampler:Euler a FaceFix:false CfgScale:7 Seed:-1 Height:1024 Width:1024 HdFix:false HdRedrawRate:0.3 HdScale:2 HdScaleAlg:ESRGAN_4x HdSteps:0} RetryCount:0}
panic: runtime error: index out of range [0] with length 0

goroutine 10 [running]:
chatplus/service/sd.(*Service).Txt2Img(0x4000538f00, {0x4b, {0x40001b0270, 0x2a}, {0x40001820c2, 0x3}, {0x40001820c5, 0x5}, 0x60, {0x40001b02a0, ...}, ...})
        /root/chatgpt-plus/api/service/sd/service.go:103 +0x9ec
chatplus/service/sd.(*Service).Run(0x4000538f00)
        /root/chatgpt-plus/api/service/sd/service.go:64 +0x178
main.main.func9.1()
        /root/chatgpt-plus/api/main.go:180 +0x20
created by main.main.func9 in goroutine 1
        /root/chatgpt-plus/api/main.go:179 +0x64
2023-10-23T22:26:09.783+0800    INFO    api/main.go:66  Loading config file: config.toml
[Fx] PROVIDE    *types.AppConfig <= main.main.func2()
[Fx] PROVIDE    *core.AppServer <= chatplus/core.NewServer()

**Comment by yangjian102621** [comment]
应该是你的 text2img.json 格式不正确导致的。对应的参数 key 都要对上的。你在仔细核对一下你提供的 json 文档参数的格式对不对。
![image](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/da0d6763-065e-47ed-b810-bf5ca3106d19)

**Comment by zelangchen** [comment]
我的已经调到SD 服务了，但是SD端报错

**Comment by zelangchen** [comment]
[SdConfig]
Enabled = true
ApiURL = "http://54755ea8.r16.cpolar.top/sdapi/v1/txt2img"
ApiKey = ""
Txt2ImgJsonPath = "res/text2img.json"
这里的ApiURL 配置的是域名还是接口名？

**Comment by dfggggx198601** [comment]
> [SdConfig] Enabled = true ApiURL = "http://54755ea8.r16.cpolar.top/sdapi/v1/txt2img" ApiKey = "" Txt2ImgJsonPath = "res/text2img.json" 这里的ApiURL 配置的是域名还是接口名？

接口

**Comment by dfggggx198601** [comment]
> 应该是你的 text2img.json 格式不正确导致的。对应的参数 key 都要对上的。你在仔细核对一下你提供的 json 文档参数的格式对不对。 ![image](https://user-images.githubusercontent.com/4746061/277521154-da0d6763-065e-47ed-b810-bf5ca3106d19.png)
但我看您说明里说可以自定义请求json报文，是需要从源代码开始改起？

**Comment by zelangchen** [comment]
[SdConfig] Enabled = true ApiURL = "http://54755ea8.r16.cpolar.top/sdapi/v1/txt2img" ApiKey = "" Txt2ImgJsonPath = "res/text2img.json" 这里的ApiURL 配置的是域名还是接口名？

接口
如果配置了接口名，在sd/service.go 的这行代码，调用就会报错

response, err := client.R().SetBody(body).SetSuccessResult(&res).Post(s.config.ApiURL + "/run/predict")

**Comment by dfggggx198601** [comment]
> [SdConfig] Enabled = true ApiURL = "http://54755ea8.r16.cpolar.top/sdapi/v1/txt2img" ApiKey = "" Txt2ImgJsonPath = "res/text2img.json" 这里的ApiURL 配置的是域名还是接口名？
> 
> 接口 如果配置了接口名，在sd/service.go 的这行代码，调用就会报错
> 
> response, err := client.R().SetBody(body).SetSuccessResult(&res).Post(s.config.ApiURL + "/run/predict")

可是，秋叶的整合包给的api就是接口，看来要改源代码？

**Comment by zelangchen** [comment]
SD 接口程序有调试过吗？
response, err := client.R().SetBody(body).SetSuccessResult(&res).Post(s.config.ApiURL + "/run/predict")
如果配置了接口，是否要把/run/predict 改掉呢？

**Comment by dfggggx198601** [comment]
> SD 接口程序有调试过吗？ response, err := client.R().SetBody(body).SetSuccessResult(&res).Post(s.config.ApiURL + "/run/predict") 如果配置了接口，是否要把/run/predict 改掉呢？

删掉了，推送绘画任务容器还是会重启

**Comment by yangjian102621** [comment]
> > [SdConfig] Enabled = true ApiURL = "http://54755ea8.r16.cpolar.top/sdapi/v1/txt2img" ApiKey = "" Txt2ImgJsonPath = "res/text2img.json" 这里的ApiURL 配置的是域名还是接口名？
> > 接口 如果配置了接口名，在sd/service.go 的这行代码，调用就会报错
> > response, err := client.R().SetBody(body).SetSuccessResult(&res).Post(s.config.ApiURL + "/run/predict")
> 
> 可是，秋叶的整合包给的api就是接口，看来要改源代码？

不需要改源码，秋叶的我试过了，没有问题的。你需要替换完整的报文，而不是只替换参数部分，函数的编码不一样的。

**Comment by yangjian102621** [comment]
> SD 接口程序有调试过吗？ response, err := client.R().SetBody(body).SetSuccessResult(&res).Post(s.config.ApiURL + "/run/predict") 如果配置了接口，是否要把/run/predict 改掉呢？

不需要，一般都有这个接口的。其他发行版都是基于 stable-diffusion-webui 这个项目的，所以 API 接口都是兼容的，只是有些发行版的参数不一样，所以提供配置 json 报文的配置项。

**Comment by zelangchen** [comment]
SD 接口程序有调试过吗？ response, err := client.R().SetBody(body).SetSuccessResult(&res).Post(s.config.ApiURL + "/run/predict") 如果配置了接口，是否要把/run/predict 改掉呢？

不需要，一般都有这个接口的。其他发行版都是基于 stable-diffusion-webui 这个项目的，所以 API 接口都是兼容的，只是有些发行版的参数不一样，所以提供配置 json 报文的配置项。

按照你这么说，s.config.ApiURL 这里只能配置域名了。http://54755ea8.r16.cpolar.top/sdapi/v1/txt2img/run/predict  这样的接口是没有的。
http://54755ea8.r16.cpolar.top/run/predict，只有这样的接口

**Comment by yangjian102621** [comment]
你只需要配置域名（http://54755ea8.r16.cpolar.top）就好了，具体接口名称是写在程序里面的。我们并没有走 sdapi 接口，而是走 websocket

**Comment by zelangchen** [comment]
程序已经进入SD，但是在SD中报错，有知道是什么原因吗？
Traceback (most recent call last):
  File "E:\SD\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\SD\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\SD\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\SD\sd-webui-aki-v4.4\python\lib\site-packages\gradio\components\image.py", line 274, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "E:\SD\sd-webui-aki-v4.4\python\lib\site-packages\gradio\processing_utils.py", line 59, in decode_base64_to_image
    img = Image.open(BytesIO(base64.b64decode(image_encoded)))

**Comment by zelangchen** [comment]
"res/text2img.json"  这个文档建议说明对应的字段怎么修改

**Comment by yangjian102621** [comment]
```
2023-10-25T23:19:51.909+0800 ERROR sd/service.go:226 {"detail":"Not Found"}
```
说明是你 SD 的 API 服务没有起来或者 API 地址填写错误，又或者你启动的这个 stable-diffusion 没有这个 API。建议按照项目的教程启动通用版的 stable-diffusion-webui 项目。https://github.com/AUTOMATIC1111/stable-diffusion-webui，还有即使使用的同一个项目部署可能 `fn_index` 参数也会不一样，如果有这种情况还是需要替换 JSON 参数文件的。

**Comment by dfggggx198601** [comment]
又有新的问题了，提交绘画任务后，容器会报错并重启
用的是原始的json文件，并且用postman测试可以出图，

panic: runtime error: index out of range [0] with length 0
goroutine 369 [running]:
chatplus/service/sd.(*Service).runTask.func1()
        /root/chatgpt-plus/api/service/sd/service.go:168 +0x448
created by chatplus/service/sd.(*Service).runTask in goroutine 346
        /root/chatgpt-plus/api/service/sd/service.go:139 +0x344

**Comment by yangjian102621** [comment]
> 又有新的问题了，提交绘画任务后，容器会报错并重启 用的是原始的json文件，并且用postman测试可以出图，
> 
> panic: runtime error: index out of range [0] with length 0 goroutine 369 [running]: chatplus/service/sd.(*Service).runTask.func1() /root/chatgpt-plus/api/service/sd/service.go:168 +0x448 created by chatplus/service/sd.(*Service).runTask in goroutine 346 /root/chatgpt-plus/api/service/sd/service.go:139 +0x344

这说明你给的 json 文件有问题，解释失败，无法从 json 文件中提取默认参数

**Comment by lp380490944** [comment]
我也遇到了这个问题，我来告诉你为什么mj绘画不行了，因为作者的version字段是写死的，现在version版本需要升级了，改完之后就好了，现在version是这个："version": "1166847114203123795"

**Comment by dfggggx198601** [comment]
现在的问题是在最后还是会报错，我在api/service/sd/service.go中做了一些修改，主要是第163行开始
var images []struct {
			Name   string      `json:"name"`
			Data   interface{} `json:"data"`
			IsFile bool        `json:"is_file"`
		}
		err = utils.ForceCovert(res.Data[0], &images)
		if err != nil {
			cbReq.Message = "error with decode image:" + err.Error()
			cbReq.Success = false
			result <- cbReq
			return
		}
以上部分，我修改为了
var images []Image
		logger.Infof("one is ok")
		bodyBytes, _ := io.ReadAll(response.Body)
		bodyStr := string(bodyBytes)
		imagesData := []interface{}{}
		err = json.Unmarshal([]byte(bodyStr),&imagesData)
		for _, imageData := range imagesData {
			image := Image{}
			err := json.Unmarshal(imageData.([]byte), &image)
			if err != nil {
				fmt.Println("error:", err)
			}
			images = append(images, image)
		}
		//err = utils.ForceCovert(res.Data[0], &images)
		logger.Infof("two is ok")
		if err != nil {
			cbReq.Message = "error with decode image:" + err.Error()
			cbReq.Success = false
			result <- cbReq
			return
		}
这样就不会会报错，但在原代码的第293行，会提示  任务执行失败：error with decode image:json: cannot unmarshal object into Go value of type []interface {}，能帮忙看看吗？

**Comment by yangjian102621** [comment]
你这个 API 返回的数据格式应该跟官方的那个不一样，所以数据解析失败，像这种你要单独做一个实现，我这边下个版本把响应解析这块设计成接口，提供默认版本的实现，然后你把你的这个版本做一个单独的实现即可。
