### ISSUE TITLE
3.1.8

### ISSUE THREAD

**Issue by talaon2** [yangjian102621/chatgpt-plus#53]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

对话时，后端报错

2023-11-22T13:45:00.615Z        INFO    chatimpl/openai_handler.go:33   HTTP请求完成，耗时：1.08993866s
2023-11-22T13:45:00.615Z        ERROR   chatimpl/chat_handler.go:150    error with decode response: invalid character '<' looking for beginning of value

2023/11/22 13:45:00 /home/www/yangjian102621/chatgpt-plus/api/handler/chatimpl/chat_handler.go:337 record not found
[1.847ms] [rows:0] SELECT * FROM `chatgpt_chat_history` WHERE user_id = 97.000000 AND `chatgpt_chat_history`.`deleted_at` IS NULL ORDER BY `chatgpt_chat_history`.`id` DESC LIMIT 1

前端报错：
ERROR
[object Object]
    at handleError (webpack-internal:///./node_modules/_webpack-dev-server@4.15.1@webpack-dev-server/client/overlay.js:299:58)
    at eval (webpack-internal:///./node_modules/_webpack-dev-server@4.15.1@webpack-dev-server/client/overlay.js:322:7)

api/chat/tokens (第二个) text  为空值时，
gpt-3.5-turbo-16k
text  
返回code:1  message: "record not found"

### 重现步骤 🕹

全新安装后

### 你的应用配置信息

Listen = "0.0.0.0:5678"
ProxyURL = ""
MysqlDns = "--------:--------@tcp(localhost:3306)/chatgpt_plus?charset=utf8mb4&parseTime=true"
StaticDir = "./static"
StaticUrl = "http://localhost/5678/static"
AesEncryptKey = "q4g17xsxkkz9ueamj01j0l2h"
WeChatBot = false

[Session]
  SecretKey = "ul7ecndq0gyy2rcbwuo24tp5y394okhi7e69oxwf3zx53qxac9k9wpqehjvuzwjz"
  MaxAge = 86400

[Manager]
  Username = "admin"
  Password = "admin123"

[Redis]
  Host = "localhost"
  Port = 6379
  Password = ""
  DB = 0

[ApiConfig]
  ApiURL = ""
  AppId = ""
  Token = ""

[SmsConfig]
  AccessKey = ""
  AccessSecret = ""
  Product = ""
  Domain = ""
  Sign = ""
  CodeTempId = ""

[OSS]
  Active = "local"
  [OSS.Local]
    BasePath = "./static/upload"
    BaseURL = "http://localhost/5678/static/upload"
  [OSS.Minio]
    Endpoint = ""
    AccessKey = ""
    AccessSecret = ""
    Bucket = ""
    UseSSL = false
    Domain = ""
  [OSS.QiNiu]
    Zone = ""
    AccessKey = ""
    AccessSecret = ""
    Bucket = ""
    Domain = ""
  [OSS.AliYun]
    Endpoint = ""
    AccessKey = ""
    AccessSecret = ""
    Bucket = ""
    Domain = ""

[MjConfig]
  Enabled = false
  UserToken = ""
  BotToken = ""
  GuildId = ""
  ChanelId = ""

[SdConfig]
  Enabled = false
  ApiURL = ""
  ApiKey = ""
  Txt2ImgJsonPath = "res/text2img.json"

[XXLConfig]
  Enabled = false
  ServerAddr = ""
  ExecutorIp = ""
  ExecutorPort = ""
  AccessToken = ""
  RegistryKey = ""

[AlipayConfig]
  Enabled = false
  SandBox = false
  AppId = ""
  UserId = ""
  PrivateKey = ""
  PublicKey = ""
  AlipayPublicKey = ""
  RootCert = ""
  NotifyURL = ""

**Comment by yangjian102621** [comment]
为什么你的用户 ID 是浮点数呢？请确认你数据库导入的数据没有问题。

**Comment by talaon2** [comment]
mysql是5.5，不支持  utf8mb4_0900_ai_ci
所以导入时我改成了 utf8mb4_general_ci 

不知道是否与这个直接相关，
经再次测试，文心一言正常，

PS：另外能不能加个proxy设置，chatGPT通过proxy中转，这样是否会更灵活

**Comment by yangjian102621** [comment]
MySQL 建议用8，少很多麻烦。 proxy 一只都有支持的，ProxyURL  这个参数就是
